package com.lyy.shiro.entity;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;

@Table(name = "tbl_user")
public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.userId
     *
     * @mbg.generated Thu Nov 29 13:45:37 CST 2018
     */
    @Id
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.userName
     *
     * @mbg.generated Thu Nov 29 13:45:37 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.userAge
     *
     * @mbg.generated Thu Nov 29 13:45:37 CST 2018
     */
    private Integer userage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.userId
     *
     * @return the value of tbl_user.userId
     *
     * @mbg.generated Thu Nov 29 13:45:37 CST 2018
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.userId
     *
     * @param userid the value for tbl_user.userId
     *
     * @mbg.generated Thu Nov 29 13:45:37 CST 2018
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.userName
     *
     * @return the value of tbl_user.userName
     *
     * @mbg.generated Thu Nov 29 13:45:37 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.userName
     *
     * @param username the value for tbl_user.userName
     *
     * @mbg.generated Thu Nov 29 13:45:37 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.userAge
     *
     * @return the value of tbl_user.userAge
     *
     * @mbg.generated Thu Nov 29 13:45:37 CST 2018
     */
    public Integer getUserage() {
        return userage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.userAge
     *
     * @param userage the value for tbl_user.userAge
     *
     * @mbg.generated Thu Nov 29 13:45:37 CST 2018
     */
    public void setUserage(Integer userage) {
        this.userage = userage;
    }
}